[Sleep]
# Disable hibernation
# Doc: https://archived.forum.manjaro.org/t/turn-off-disable-hibernate-completely/139939
# This file should be located at /etc/systemd/sleep.conf.d/
AllowHibernation=no
AllowHybridSleep=no
AllowSuspendThenHibernate=no
