# Basic fangfrisch configuration

[DEFAULT]
db_url = sqlite:////var/lib/fangfrisch/db.sqlite

local_directory = /var/lib/clamav
max_size = 5MB
on_update_exec = clamdscan --reload
on_update_timeout = 42

[sanesecurity]
enabled = yes

[urlhaus]
enabled = yes
max_size = 2MB